# Generated by Django 4.2.6 on 2023-11-29 13:05

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import embed_video.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('program', '0002_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=40, null=True, unique=True, verbose_name='ip address'),
        ),
        migrations.AlterField(
            model_name='program',
            name='counseling',
            field=models.BooleanField(blank=True, null=True, verbose_name='counseling'),
        ),
        migrations.AlterField(
            model_name='program',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='program',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='deliverance',
            field=models.BooleanField(blank=True, null=True, verbose_name='deliverance'),
        ),
        migrations.AlterField(
            model_name='program',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='program',
            name='display',
            field=models.BooleanField(blank=True, null=True, verbose_name='display'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='program', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='program',
            name='like_count',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='like_count'),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='program',
            name='speicalprogram',
            field=models.BooleanField(blank=True, null=True, verbose_name='specialprogram'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='program',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='programnum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='programnum',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
