# Generated by Django 4.2.6 on 2023-11-29 13:05

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mfm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='about')),
            ],
            options={
                'verbose_name_plural': 'Mfm',
            },
        ),
        migrations.AlterField(
            model_name='weekservice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='weekservice',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='weekly', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='weekservice',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weekservice',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='weekservice',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='weekservice',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='weekservice',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
