# Generated by Django 4.2.6 on 2023-12-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mfm_alter_weekservice_created_alter_weekservice_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='fullame')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.AddField(
            model_name='weekservice',
            name='display',
            field=models.BooleanField(default=False, help_text='To be displayed at program page'),
        ),
    ]
